name: CD workflow

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Select deployment environment"
                required: true
                type: environment

jobs:
    Render_deployment:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Render deployment
              env:
                  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: curl $deploy_url
