name: CD workflow

on:
    release:
        types:
            - published

jobs:
    Render_deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Render deployment
              env:
                  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: curl $deploy_url
